# Generated by Django 2.2.2 on 2019-07-12 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(verbose_name='description')),
                ('category', models.CharField(choices=[('0', 'Launch'), ('1', 'Deserts'), ('2', 'Drinks'), ('3', 'Main Dishes')], max_length=2)),
                ('price', models.IntegerField(max_length=50)),
                ('make_on', models.DateField(auto_now_add=True)),
                ('updated_make', models.DateField(auto_now=True)),
                ('cover_image', models.ImageField(upload_to='uploads')),
                ('cookname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Menus',
            },
        ),
    ]
